services:
  - type: web
    name: giveaway-app
    env: docker
    buildCommand: docker build -t giveaway-app .
    envVars:
      - key: PORT
        value: 8080
      - key: HOST
        fromService:
          type: web
          name: giveaway-app
          property: host
    autoDeploy: true
